### ISSUE TITLE
Platform Selection

### ISSUE THREAD

**Issue by moeezumer6754** [moeezumer6754/Group02-Discrete#2]
We need to finalize the platform for developing and deploying our project. The decision will impact the overall design, performance, and scalability. This issue is created to evaluate and compare potential platforms to ensure the best fit for our project's requirements.

Goals
Research available platforms.

Evaluate platforms based on the following criteria:
1.Performance
2.Ease of development
3.Community support

Potential Platforms
Android Studios (Mobile Application)
Visual Studio Code (Web Application using HTML+CSS+JS)

Tasks
Research the pros and cons of each platform.

Expected Outcome
A clear and informed decision about the platform to use for the project.

**Comment by Zaryan07** [comment]
If we choose web dev process for this we have to consider it's pros and cons too.
_**Pros**_
**Accessibility:** A web application is accessible from any device with a browser, making it more convenient for users.
**Ease of Deployment:** Updates and improvements can be deployed server-side without needing users to download new versions, ensuring everyone has access to the latest features and security fixes.
**User Experience:** A web-based interface allows for a clean and interactive design, where users can get instant feedback on password strength as they type.
**Scalability:** Web applications can be easily scaled for more users, making them suitable for broader audiences or integration into other web-based systems.

**_Cons_**
**Security Risks:** Password data, even if only checked and not stored, poses security concerns when transmitted over the internet. Proper encryption and HTTPS are essential to safeguard user input.
Dependency on Internet Access: Users need a stable internet connection to access the checker, which could be a limitation in areas with poor connectivity.
**Backend Overhead:** Developing a secure backend (if required) can be challenging and may involve costs for hosting and server maintenance.
**Latency:** Some users may experience slight delays, especially if they’re on slow connections, which can affect real-time feedback on password strength.

**Comment by shamoonasadk** [comment]
Using **Android Studio** to create a **Password Strength Checker Mobile Application** has several advantages, some of which are listed below.

**_Pros_**
**Offline Functionality:** A mobile app can work offline, allowing users to check password strength without needing an internet connection, which can be a major convenience.
**Native Performance:** Android Studio enables you to build a native app with optimized performance for Android devices, offering a smoother and faster user experience.
**Device Integration:** You can integrate additional features native to Android devices, like biometric authentication (e.g., fingerprint scanning) for enhanced security checks.
**Increased Security:** Since the app runs locally on the user’s device, there’s less risk of password data being intercepted or compromised over the internet, provided it doesn't require external servers.
**Accessibility:** A mobile app is easily accessible directly on the user’s device, which may encourage them to use it more regularly.

On the contrary, there are some disadvantages that must not be overlooked.

**_Cons:_**
**Platform Limitation:** Developing only on Android Studio restricts the app to Android users. To reach iOS users, you’d need to develop a separate app or consider cross-platform tools.
**Development and Maintenance Overheads:** Android apps need regular updates and compatibility adjustments for different device versions, which can increase development time and maintenance.
**Download and Update Dependency:** Users have to download the app, and some may be hesitant due to privacy concerns or limited storage. Additionally, not all users keep their apps updated.
**Complexity with Data Security:** Although mobile apps are generally secure, you still need to consider data protection measures, especially if you plan to add features like saving password history, which could pose privacy risks.
**Resource Constraints:** Mobile devices have limited processing power and memory compared to desktop or server-based solutions, which might limit advanced features, like complex password entropy calculations.

**Comment by Fasih160** [comment]
Pros of Web Apps over Android Apps: 

• Cross-Platform: Accessible on any device with a browser, removing the need for multiple app versions.
• No Installation Needed: Can be accessed directly via URL, saving storage.
• Easy Updates: Server-side updates mean users always have the latest version.
• Cost-Effective: Develop once for multiple platforms, reducing time and cost.
• Searchable: Can be indexed by search engines for greater discoverability.
• Easily Shared: URLs make sharing simple, with no app store requirement.
• Device Agnostic: Works on any device with a browser.
• Reduced Storage: Minimal device space usage.
• Unified Experience: Consistent interface across platforms.


Cons of Web Apps: 

• Limited Offline Use: Mostly need internet to function.
• Restricted Device Access: Limited interaction with device features like GPS and camera.
• Slower Performance: Web apps rely on browsers, which can impact speed.
• Security Risks: Greater exposure to online threats.
• Less Branding Opportunity: No home screen presence or app store listing.

**Comment by Fasih160** [comment]
Given the critical decision we face regarding the development platform for our project, I strongly advocate for prioritizing a web application using Visual Studio Code (HTML+CSS+JS) over a mobile application created in Android Studio. Here are the key points supporting this choice:

- **Performance**: Web applications can be optimized for a wide range of devices and screen sizes, ensuring consistent performance across various platforms. Unlike mobile apps, web apps do not require multiple versions for different operating systems, significantly reducing maintenance overhead.

- **Ease of Development**: Developing a web app with HTML, CSS, and JavaScript in Visual Studio Code offers a more straightforward and versatile development process. The extensive range of libraries and frameworks available for web development simplifies complex tasks and accelerates development timelines.

- **Community Support**: The web development community is vast and active, providing an abundance of resources, tutorials, and forums for troubleshooting and improving our application. This support network can be invaluable for addressing any challenges quickly and effectively.

- **Scalability**: Web applications are inherently more scalable than mobile apps. They allow for easy updates and iterations without requiring users to download new versions, making it simpler to roll out new features and improvements.

- **Accessibility**: With a web app, we can ensure that our application is accessible to the widest possible audience. Users can access our web app from any device with an internet connection, be it a smartphone, tablet, or desktop, without the need for an additional app download.

Given these points, I believe that focusing on a web application will offer us greater flexibility, reduced development time, and broader reach, ultimately leading to a more successful project.

**Comment by moeezumer6754** [comment]
After reviewing the discussions on the platform selection issue between web and mobile applications, I have decided to proceed with developing this project (Password Strength Checker) using Android Studio. This decision was made considering the benefits of mobile platforms, such as better user engagement, offline functionality, and direct access to device-specific features. Android Studio was chosen for its comprehensive tools and support for Android app development.

**Comment by moeezumer6754** [comment]
After reviewing the discussions on the platform selection issue between web and mobile applications, I have decided to proceed with developing this project (Password Strength Checker) using Android Studio. This decision was made considering the benefits of mobile platforms, such as better user engagement, offline functionality, and direct access to device-specific features. Android Studio was chosen for its comprehensive tools and support for Android app development.
